In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [2]:
load_iris().data
load_iris().target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [3]:
iris = load_iris()
x =iris.data
y= iris.target

In [4]:
print(x.shape)
print(x)


(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [5]:
print(y.shape)
print(y)

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
frame = pd.DataFrame(x,y, columns= iris.feature_names)
frame["etiqueta"] =iris.target
frame

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),etiqueta
0,5.1,3.5,1.4,0.2,0
0,4.9,3.0,1.4,0.2,0
0,4.7,3.2,1.3,0.2,0
0,4.6,3.1,1.5,0.2,0
0,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
2,6.7,3.0,5.2,2.3,2
2,6.3,2.5,5.0,1.9,2
2,6.5,3.0,5.2,2.0,2
2,6.2,3.4,5.4,2.3,2


In [7]:
frame = pd.DataFrame(x,y, columns= iris.feature_names)
frame["etiqueta"] =iris.target
frame["nombre_etiqueta"] = iris.target_names[iris.target]
print(frame)

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
0                 4.9               3.0                1.4               0.2   
0                 4.7               3.2                1.3               0.2   
0                 4.6               3.1                1.5               0.2   
0                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
2                 6.7               3.0                5.2               2.3   
2                 6.3               2.5                5.0               1.9   
2                 6.5               3.0                5.2               2.0   
2                 6.2               3.4                5.4               2.3   
2                 5.9               3.0                5.1               1.8   

    etiqueta nombre_etiqueta  
0       

In [8]:
print(frame[frame["etiqueta"] == 1]) #EJEM. DE FILTRO PANDAS (VIRGINICA)
#print(frame) #Mostramos toda la data

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                7.0               3.2                4.7               1.4   
1                6.4               3.2                4.5               1.5   
1                6.9               3.1                4.9               1.5   
1                5.5               2.3                4.0               1.3   
1                6.5               2.8                4.6               1.5   
1                5.7               2.8                4.5               1.3   
1                6.3               3.3                4.7               1.6   
1                4.9               2.4                3.3               1.0   
1                6.6               2.9                4.6               1.3   
1                5.2               2.7                3.9               1.4   
1                5.0               2.0                3.5               1.0   
1                5.9               3.0              

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [10]:
model = DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [11]:
print("Predicción Individual")
muestra_prueba = np.array([[5.6,2.9,3.6,1.3 ]])
print(model.predict(muestra_prueba))


Predicción Individual
[1]


## ----------------PRUEBA ORDENADA-----------------
----------

In [20]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier #Clasificación multiclase
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [21]:
iris= load_iris() #cargamos el dataset
x= iris.data #obtenemos los datos (x)
y= iris.target #obtenemos las etiquetas (y)

In [22]:
print(x.shape) #obtenemos la forma de x (2D)
print(x) 

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

In [23]:
print(y.shape) #forma de y (1D)
print(y)

(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [24]:
#---ANÁLISIS EXPLORATORIO DEL DATASET---
frame = pd.DataFrame(x,y,columns= iris.feature_names) #CREAMOS EL DATAFRAME CON PANDAS
frame['etiqueta']= iris.target #AGREGAMOS UNA COLUMNA NUEVA CON LAS ETIQUETAS REALES
frame['nombre_etiqueta']= iris.target_names[iris.target] #AGREGAMOS UNA COLUMNA CON LOS NOMBRES DE ETIQUETA
print(frame[frame['etiqueta']==1]) #EJEM. DE FILTRO CON PANDAS (VIRGÍNICA)
#print(frame) #MOSTRAMOS TODA LA DATA

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                7.0               3.2                4.7               1.4   
1                6.4               3.2                4.5               1.5   
1                6.9               3.1                4.9               1.5   
1                5.5               2.3                4.0               1.3   
1                6.5               2.8                4.6               1.5   
1                5.7               2.8                4.5               1.3   
1                6.3               3.3                4.7               1.6   
1                4.9               2.4                3.3               1.0   
1                6.6               2.9                4.6               1.3   
1                5.2               2.7                3.9               1.4   
1                5.0               2.0                3.5               1.0   
1                5.9               3.0              

In [25]:
#DIVIDIMOS EL DATASET EN 2 PARTES: ENTRENAMIENTO (80%) Y PRUEBA (20%)
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state= 42)

In [26]:
#CREACIÓN Y ENTRENAMIENTO DEL MODELO (ÁRBOL DE DECISIONES PARA CLASIFICACIÓN MULTICLASE)
model= DecisionTreeClassifier()
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [27]:
#PREDICCIÓN INDIVIDUAL
print('Predicción individual')
muestra_prueba= np.array([[6.4,3.2,4.5,1.5]]) #EXTRAEMOS UNA MUESTRA INDIVIDUAL
prediccion= model.predict(muestra_prueba) #OBTENEMOS LA ETIQUETA REAL DE LA PREDICCIÓN
print(prediccion)
print(iris.target_names[prediccion]) #OBTENEMOS EL NOMBRE DE LA ETIQUETA OBTENIDA

Predicción individual
[1]
['versicolor']
